[package]
name = "segdriver"
version = "0.1.0"
edition = "2024"

[dependencies]
atoll = { version = "0.1.3", registry = "substrate", path = "../../../libs/atoll" }
substrate = { version = "0.10.2", registry = "substrate", path = "../../../substrate" }
sky130 = { version = "0.10.2", registry = "substrate", path = "../../../pdks/sky130" }
layir = { version = "0.2.1", registry = "substrate", path = "../../../libs/layir" }
gdsconv = { version = "0.2.1", registry = "substrate", path = "../../../libs/gdsconv" }
gds = { version = "0.4.1", registry = "substrate", path = "../../../libs/gds" }
scir = { version = "0.9.1", registry = "substrate", path = "../../../libs/scir" }
spice = { version = "0.9.2", registry = "substrate", path = "../../../libs/spice" }

arcstr = "1"
rust_decimal = "1"
rust_decimal_macros = "1"
derive-where = "1"
approx = "0.5"

