use std::{collections::HashMap, sync::Arc};

use arcstr::ArcStr;
use serde::{Deserialize, Serialize};

use crate::{
    block::Block,
    schematic::{
        cell::SchematicCell,
        context::SchematicCtx,
        instance::{Instance, SchematicInstance},
        interface::{AnalogInterface, Port, SignalMap},
        HasSchematic,
    },
};

use super::resistor::Resistor;

#[derive(Debug, Clone, Copy)]
pub struct VDividerIntf {
    pub vdd: Port,
    pub vss: Port,
    pub vout: Port,
}

// AUTOGENERATED CODE BEGIN
#[derive(Debug, Clone, Copy)]
pub struct VDividerIntfUninitialized;

#[allow(clippy::new_ret_no_self)]
impl VDividerIntf {
    fn new() -> VDividerIntfUninitialized {
        VDividerIntfUninitialized
    }
}

impl AnalogInterface<VDivider> for VDividerIntf {
    type Uninitialized = VDividerIntfUninitialized;

    fn initialize(_intf: Self::Uninitialized, map: &mut SignalMap) -> Self {
        Self {
            vdd: map.register_port(),
            vss: map.register_port(),
            vout: map.register_port(),
        }
    }

    fn uninitialized(self) -> VDividerIntfUninitialized {
        VDividerIntfUninitialized
    }
}
// AUTOGENERATED CODE END

#[derive(Serialize, Deserialize)]
pub struct VDivider {
    pub r1: usize,
    pub r2: usize,
}

impl Block for VDivider {
    fn id() -> ArcStr {
        arcstr::literal!("vdivider")
    }

    fn name(&self) -> ArcStr {
        arcstr::format!("vdivider_{}_{}", self.r1, self.r2)
    }
}

// AUTOGENERATED CODE BEGIN
#[derive(Debug, Clone)]
pub struct VDividerCell {
    intf: VDividerIntf,
    instances: Vec<Instance>,
    signal_map: SignalMap,
}

impl SchematicCell<VDivider> for VDividerCell {
    fn new(intf: VDividerIntfUninitialized) -> Self {
        let mut map = SignalMap::new();
        VDividerCell {
            intf: VDividerIntf::initialize(intf, &mut map),
            instances: Vec::new(),
            signal_map: map,
        }
    }

    fn add_instance<T, N>(&mut self, name: N, cell: Arc<T::Cell>) -> T::Instance
    where
        T: HasSchematic,
        N: Into<ArcStr>,
    {
        let intf = self.initialize_interface::<T>(cell.interface().clone().uninitialized());
        let inst = T::Instance::new(name, intf, cell);
        self.instances.push(inst.clone().into());
        inst
    }

    fn instances(&self) -> &Vec<Instance> {
        &self.instances
    }

    fn signal_map(&self) -> &SignalMap {
        &self.signal_map
    }

    fn signal_map_mut(&mut self) -> &mut SignalMap {
        &mut self.signal_map
    }

    fn interface(&self) -> &VDividerIntf {
        &self.intf
    }
}

#[derive(Debug, Clone)]
pub struct VDividerInstance {
    name: ArcStr,
    intf: VDividerIntf,
    cell: Arc<VDividerCell>,
}

#[allow(clippy::from_over_into)]
impl Into<Instance> for VDividerInstance {
    fn into(self) -> Instance {
        Instance {
            name: self.name,
            instances: self.cell.instances().clone(),
            ports: HashMap::from_iter([
                ("vdd".into(), self.intf.vdd),
                ("vss".into(), self.intf.vss),
                ("vout".into(), self.intf.vout),
            ]),
        }
    }
}

impl SchematicInstance<VDivider> for VDividerInstance {
    fn new(name: impl Into<ArcStr>, intf: VDividerIntf, cell: Arc<VDividerCell>) -> Self {
        VDividerInstance {
            name: name.into(),
            intf,
            cell,
        }
    }

    fn name(&self) -> ArcStr {
        self.name.clone()
    }

    fn intf(&self) -> &VDividerIntf {
        &self.intf
    }
}
// AUTOGENERATED CODE END

impl HasSchematic for VDivider {
    type Interface = VDividerIntf;
    type Cell = VDividerCell;
    type Instance = VDividerInstance;

    fn schematic(&self, ctx: &mut SchematicCtx) -> Self::Cell {
        let mut cell = Self::Cell::new(VDividerIntf::new());

        let res1 = ctx.generate(Resistor { r: self.r1 });
        let res2 = ctx.generate(Resistor { r: self.r2 });

        let res1 = cell.add_instance::<Resistor, _>("Xr1", res1);
        let res2 = cell.add_instance::<Resistor, _>("Xr2", res2);

        cell.connect(res1.intf().p, cell.intf.vdd);
        cell.connect(res1.intf().n, res2.intf().p);
        cell.connect(res2.intf().n, cell.intf.vss);

        cell
    }
}
