gen-examples: 
  find code -type f -name *.rs -exec bash -c "awk '{print \"# \" \$0}' {} > {}.hidden" \;
  for f in codegen substrate; do \
    mkdir -p ../../$f/build/docs && \
    cp -r code/* ../../$f/build/docs/ \
  ; done

build: gen-examples
  cargo d --no-deps --workspace --all-features --target-dir ./target
  echo "<meta http-equiv=\"refresh\" content=\"0; url=substrate\">" > ./target/doc/index.html

open: build
  open ./target/doc/index.html

deploy: build
  fly deploy

